Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,9 +44,10 @@ jobs:
           find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6 -name "libpyside6qml*.dylib" || echo "No libpyside6qml dylib files found"
           echo "Listing Qt frameworks in PySide6:"
           find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6 -name "*.framework" || echo "No Qt frameworks found in PySide6"
-          find /usr/local/opt -name "QtCore.framework" || echo "QtCore.framework not found"
-          find /usr/local/opt -name "QtGui.framework" || echo "QtGui.framework not found"
-          find /usr/local/opt -name "QtWidgets.framework" || echo "QtWidgets.framework not found"
+          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6/Qt/lib -name "QtCore.framework" || echo "QtCore.framework not found"
+          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6/Qt/lib -name "QtGui.framework" || echo "QtGui.framework not found"
+          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6/Qt/lib -name "QtWidgets.framework" || echo "QtWidgets.framework not found"
+          find /usr/local/opt/python@3.10/lib/python3.10/site-packages/PySide6/Qt/lib -name "QtWebEngineCore.framework" || echo "QtWebEngineCore.framework not found"
           echo "Listing rawpy directory contents:"
           ls -R /usr/local/opt/python@3.10/lib/python3.10/site-packages/rawpy || echo "rawpy directory not found"
           echo "Checking for libraw in rawpy:"
